#pragma once

enum syscall_index {
    SYSCALL_OPEN,
    SYSCALL_CLOSE,
    SYSCALL_READ,
    SYSCALL_WRITE,
    SYSCALL_SEEK,
    SYSCALL_TELL,
    SYSCALL_FSTAT,
    SYSCALL_ISATTY,
    SYSCALL_LSEEK,
    SYSCALL_EXIT,
    SYSCALL_ALLOC_PAGES,
    SYSCALL_DEALLOC_PAGES,


    SYSCALL_SCHEDULE,

    SYSCALL_GETCWD,
    SYSCALL_DIRENT_COUNT,
    SYSCALL_GET_DIRENT,

    SYSCALL_DUP2,
    SYSCALL_POLL,
    SYSCALL_STAT,
    SYSCALL_LSTAT,
    SYSCALL_PID,
    SYSCALL_FORK,
    SYSCALL_EXEC,
    SYSCALL_WAITPID,
    SYSCALL_CHANGE_DIR,
    SYSCALL_SET_ERRNO_LOCATION,
    SYSCALL_MAKE_DIR,
    SYSCALL_DUP,
    SYSCALL_READLINK,
    SYSCALL_MAKE_LINK,
    SYSCALL_REMOVE_FILE,
    SYSCALL_MMAP,
    SYSCALL_IOPL,
    SYSCALL_SELECT,
    SYSCALL_SOCKET,
    SYSCALL_BIND,
    SYSCALL_GETPEERNAME,
    SYSCALL_LISTEN,
    SYSCALL_CONNECT,
    SYSCALL_ACCEPT,
    SYSCALL_SETFLAGS,
    SYSCALL_UNAME
};



